apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
   name: my-custom-role-binding
   namespace: my-namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: my-custom-role
subjects:
- kind: ServiceAccount
  name: custom-sa
  namespace: my-namespace