apiVersion: rbac.authorization.k8s.io/v1
kind: Role   #ClusterRole -> only without a namespace
metadata:
  name: my-custom-role
  namespace: my-namespace  
rules:
  - apiGroups:
      - "*"
    resources:
      - services
      - pods
    verbs:
      - get
      - list