apiVersion: v1
kind: Pod
metadata:
    name: secret-pod
    labels:
        type: secret-pod
spec:
    containers:
      - name: cont-01
        image: alpine
        envFrom:
          - secretRef:
              name: my-secret
                